# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            akbar
tagline:          'explorations through doing'
description:      '@akbar.'
url:              http://akbarpasha.org

author:
  name:           'akbar'
  url:            

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
